---

- name: Install pip
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Install boto3 y botocore
  ansible.builtin.pip:
    name: "{{ item }}"
    state: present
  loop:
    - boto3
    - botocore

...